CREATE TABLE IF NOT EXISTS `drones` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `serial_number` VARCHAR(100) NOT NULL UNIQUE,
    `model` VARCHAR(20) NOT NULL,
    `weight_limit` DOUBLE(10,2) NOT NULL,
    `battery_capacity` INT DEFAULT NULL,
    `state` VARCHAR(20) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
