CREATE TABLE IF NOT EXISTS `battery_level_audits` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `drone_id` BIGINT NOT NULL,
    `battery_level` INT DEFAULT NULL,
    `status` VARCHAR(10) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`drone_id`) REFERENCES `drones`(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
